# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheNewFlickr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheNewFlickr
   pod 'Alamofire'
   pod 'Kingfisher'

  target 'TheNewFlickrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheNewFlickrUITests' do
    # Pods for testing
  end

end
